"""Initial migration.

Revision ID: 273ad534979a
Revises: 
Create Date: 2022-04-19 23:07:27.660802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273ad534979a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'comment')
    # ### end Alembic commands ###
