"""empty message

Revision ID: 8ef79d8f6a7a
Revises: fcf9958b0ed4
Create Date: 2022-04-28 23:06:50.304896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef79d8f6a7a'
down_revision = 'fcf9958b0ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'points')
    # ### end Alembic commands ###
