"""empty message

Revision ID: ac9b9fe46518
Revises: 273ad534979a
Create Date: 2022-04-24 15:28:39.155505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9b9fe46518'
down_revision = '273ad534979a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'points')
    # ### end Alembic commands ###
