"""empty message

Revision ID: cd93d9ed803f
Revises: ac9b9fe46518
Create Date: 2022-04-28 23:04:19.199046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd93d9ed803f'
down_revision = 'ac9b9fe46518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('point', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'point')
    # ### end Alembic commands ###
